services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-event_tracker}
      POSTGRES_USER: ${POSTGRES_USER:-event_tracker}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-event_tracker_pwd}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  collector:
    image: nathan2blk/event-tracker-collector:1.0.0
    env_file:
      - .env
    environment:
      COLLECTOR_PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  query:
    image: nathan2blk/event-tracker-query:1.0.0
    env_file:
      - .env
    environment:
      QUERY_PORT: 3001
    depends_on:
      - postgres
    ports:
      - "3001:3001"

volumes:
  pgdata:
