apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-tracker
  namespace: argocd
spec:
  project: default

  source:
    repoURL: "https://github.com/Nathan2BLK/Event-Driven-User-Activity-Tracker.git"
    targetRevision: main
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: event-tracker

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true