apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: event-tracker
data:
  COLLECTOR_PORT: "3000"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "event_tracker"
  POSTGRES_USER: "event_tracker"
