apiVersion: v1
kind: Service
metadata:
  name: query
  namespace: event-tracker
spec:
  type: NodePort
  selector:
    app: query
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 30081
